# Site settings
title: Çağatay AYDIN
email: cagatayaydinn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kocaeli Üniversitesi/Bilgisayar Mühendisliği
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aydincagatay.github.io/" # the base hostname & protocol for your site
instagram_username: cagatay_yolda
github_username:  aydincagatay

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Freelance Developer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
